spring:
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB
  main:
    allow-bean-definition-overriding: true

server:
  port: 35200
  tomcat:
    accesslog:
      enabled: true
      pattern: '{"time": "%{yyyy-MM-dd''T''HH:mm:ss.SSSZ"}t, "X-Forwarded-For": "%{X-Forwarded-For}i", "ip": "%a", "requestTime": "%T", "status": "%s", "size": "%B", "userAgent": "%{User-Agent}i", "referer": "%{Referer}i", "uri": "%U", "method": "%m", "args": "%q", "Accept-Encoding": "%{Accept-Encoding}i"}'
      directory: ./
      max-days: 14
      condition-unless: doNotLog

# logging
logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error
    com:
      labshigh:
        realestate: INFO

mybatis:
  type-aliases-package: com.labshigh.realestate.internal.api
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
