app:
  profile: prod

spring:
  redis:
    host: redisc-dppvc.vpc-cdb.ntruss.com
    port: 6379
    database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-dppkk.vpc-cdb.ntruss.com/realestate?&zeroDateTimeBehavior=convertToNull&autoReconnect=true&noAccessToProcedureBodies=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Seoul
    username: realestate
    password: 6M6yTn4WL9A?X@BvofHm
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 26000
    initialization-mode: always
    initialize: true
    sql-script-encoding: utf-8
    continue-on-error: true

# server
server:
  tomcat:
    basedir: /home/labshigh/logs/realestate-internal-api

logging:
  file: /home/labshigh/logs/realestate-internal-api/common.log
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,Asia/Seoul
    rolling-file-name: /home/labshigh/logs/realestate-internal-api/common.log.%d{yyyy-MM-dd}.%i.gz
  level:
    root: ERROR
    com:
      labshigh:
        realestate: ERROR

ncloud:
  access-key: 0EB353356DD94BC5AA69
  secret-key: AE5FB443EC6C50B3F856FD084EF4FE19EA6FF7A9
  object-storage:
    end-point: kr.object.ncloudstorage.com
    region: kr-standard
    bucket: realestate-s3
  mail-storage:
    end-point: https://mail.apigw.ntruss.com/api/v1/mails
    email-template-id: 8260
    tokenExpirationTime: 24 # 60*60*24
  sms-storage:
    end-point: https://sens.apigw.ntruss.com/sms/v2
    service-id: ncp:sms:kr:278692193707:nftmoa_io
    send-url: /service/${ncloud.sms-storage.service-id}/messages
    from-phone-number: 01096361079
    expirationTime: 1440 # 60*60*24


